def questions_bank(index:int):
    questions=[
        {"question":"¿Cuándo acabó la II Guerra Mundial?",
         "options":["1945","1950","1960","1942"],
         "answer":"1945",
         },
        {"question":"¿Dónde se encuentra la Sagrada Familia?",
         "options":["Madrid","Medellin","Santiago","Barcelona"],
         "answer":"Barcelona",
         },     
        {"question":"¿Quién pintó la Mona Lisa?",
         "options":["Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh", "Claude Monet"],
         "answer":"Leonardo da Vinci",
         },
        {"question":"¿Cómo se llama el río más famoso de Egipto?",
         "options":["Nilo","Amazonas","Atbara","Cairo"],
         "answer":"Nilo",
         },
        {"question":"¿Cuál es el planeta más grande del sistema solar?",
         "options":["Marte", "Venus", "Júpiter", "Saturno"],
         "answer":"Júpiter",
         },
        {"question":"¿En qué país se encuentra la Torre Eiffel?",
         "options":["Italia", "España", "Francia", "Alemania"],
         "answer":"Francia",
         },
        {"question":"¿En qué año se llevó a cabo la Revolución Rusa?",
         "options":["1917", "1923", "1905", "1932"],
         "answer":"1917",
         },
        {"question":"¿Cuál es la capital de Australia?",
         "options":["Sidney", "Melbourne", "Canberra", "Brisbane"],
         "answer":"Canberra",
         },
        {"question":"¿Quién fue el primer ser humano en viajar al espacio?",
         "options":["Neil Armstrong", "Yuri Gagarin", "John Glenn", "Buzz Aldrin"],
         "answer":"Yuri Gagarin",
         },
        {"question":"¿Cuál es la montaña más alta del mundo?",
         "options":["Monte Kilimanjaro", "Monte McKinley", "Monte Everest", "Monte Aconcagua"],
         "answer":"Monte Everest",
         }
    ] 
    return questions[index]